# Data Cleaning & Preprocessing

In [19]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from ydata_profiling import ProfileReport

In [3]:
df = pd.read_parquet('../assets/SINAN-TB_Brazil.parquet')
df

,DT_NOTIFIC,CS_SEXO,CS_RACA,TRATAMENTO,RAIOX_TORA,TESTE_TUBE,FORMA,AGRAVAIDS,AGRAVALCOO,AGRAVDIABE,...,BACILOSC_3,BACILOSC_4,BACILOSC_5,BACILOSC_6,SITUA_ENCE,AGRAVDROGA,AGRAVTABAC,UF,DIAS_EM_TRATAMENTO,IDADE
0,06/01/2001,1,9.0,1.0,1.0,4.0,1.0,9.0,9.0,9.0,...,9.0,3.0,9.0,3.0,1.0,9.0,9.0,AC,195,66.0
1,16/01/2001,0,4.0,1.0,1.0,4.0,1.0,9.0,9.0,9.0,...,9.0,3.0,9.0,3.0,1.0,9.0,9.0,AC,181,35.0
2,16/01/2001,1,4.0,1.0,1.0,4.0,1.0,9.0,9.0,9.0,...,9.0,3.0,9.0,3.0,1.0,9.0,9.0,AC,181,54.0
3,22/01/2001,1,4.0,1.0,1.0,4.0,1.0,9.0,9.0,9.0,...,9.0,3.0,9.0,3.0,1.0,9.0,9.0,AC,181,36.0
4,03/01/2001,0,9.0,1.0,4.0,4.0,1.0,9.0,9.0,9.0,...,9.0,3.0,9.0,3.0,1.0,9.0,9.0,AC,183,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964094,31/07/2019,0,4.0,1.0,1.0,4.0,1.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,1.0,2.0,2.0,TO,190,32.0
964095,17/08/2019,0,4.0,1.0,1.0,4.0,1.0,9.0,2.0,2.0,...,2.0,3.0,2.0,2.0,1.0,2.0,2.0,TO,214,24.0
964096,04/09/2019,1,4.0,1.0,1.0,4.0,1.0,2.0,2.0,2.0,...,2.0,3.0,3.0,3.0,1.0,2.0,2.0,TO,196,22.0
964097,27/09/2019,1,4.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,...,4.0,4.0,4.0,4.0,1.0,2.0,2.0,TO,178,15.0
964098,11/12/2019,1,4.0,1.0,1.0,4.0,1.0,2.0,2.0,2.0,...,9.0,9.0,9.0,9.0,3.0,2.0,2.0,TO,54,87.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964099 entries, 0 to 964098
Data columns (total 38 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   DT_NOTIFIC          964099 non-null  object
 1   CS_SEXO             964099 non-null  int64
 2   CS_RACA             964099 non-null  float64
 3   TRATAMENTO          964099 non-null  float64
 4   RAIOX_TORA          964099 non-null  float64
 5   TESTE_TUBE          964099 non-null  float64
 6   FORMA               964099 non-null  float64
 7   AGRAVAIDS           964099 non-null  float64
 8   AGRAVALCOO          964099 non-null  float64
 9   AGRAVDIABE          964099 non-null  float64
 10  AGRAVDOENC          964099 non-null  float64
 11  AGRAVOUTRA          964099 non-null  float64
 12  BACILOSC_E          964099 non-null  float64
 13  BACILOS_E2          964099 non-null  float64
 14  BACILOSC_O          964099 non-null  float64
 15  CULTURA_ES          964099 non-null  float64
 16  HIV                 964099 non-null  float64
 17  RIFAMPICIN          964099 non-null  float64
 18  ISONIAZIDA          964099 non-null  float64
 19  ETAMBUTOL           964099 non-null  float64
 20  ESTREPTOMI          964099 non-null  float64
 21  PIRAZINAMI          964099 non-null  float64
 22  ETIONAMIDA          964099 non-null  float64
 23  OUTRAS              964099 non-null  float64
 24  TRAT_SUPER          964099 non-null  float64
 25  DOENCA_TRA          964099 non-null  float64
 26  BACILOSC_1          964099 non-null  float64
 27  BACILOSC_2          964099 non-null  float64
 28  BACILOSC_3          964099 non-null  float64
 29  BACILOSC_4          964099 non-null  float64
 30  BACILOSC_5          964099 non-null  float64
 31  BACILOSC_6          964099 non-null  float64
 32  SITUA_ENCE          964099 non-null  float64
 33  AGRAVDROGA          964099 non-null  float64
 34  AGRAVTABAC          964099 non-null  float64
 35  UF                  964098 non-null  object
 36  DIAS_EM_TRATAMENTO  964099 non-null  int64
 37  IDADE               964073 non-null  float64
dtypes: float64(34), int64(2), object(2)
memory usage: 279.5+ MB

In [5]:
translate_numbers = {
  'CS_SEXO': {
    0: 'Female',
    1: 'Male',
    2: 'Undefined',
  },
  'CS_RACA': {
    1: 'White',
    2: 'Black',
    3: 'Yellow',
    4: 'Admixed',
    5: 'Indigenous',
    9: 'Ignored',
  },
  'TRATAMENTO': {
    1: 'New case',
    2: 'Relapse',
    3: 'Re-entry after abandonment',
    4: "Don't know",
    5: 'Transfer',
    6: 'Post-death',
    9: 'Ignored',
  },
  'RAIOX_TORA': {
    1: 'Suspicious',
    2: 'Normal',
    3: 'Other pathology',
    4: 'No accomplished',
    9: 'Ignored',
  },
  'TESTE_TUBE': {
    1: 'No reactor',
    2: 'Weak reactor',
    3: 'Strong reactor',
    4: 'Not performed',
    9: 'Ignored',
  },
  'FORMA': {
    1: 'Pulmonary',
    2: 'Extrapulmonary',
    3: 'Pulmonary+Extrapulmonary',
    9: 'Ignored',
  },
  'SITUA_ENCE': {
    1: 'Cured',
    3: 'Died',
  },
  ('AGRAVAIDS', 'AGRAVALCOO', 'AGRAVDIABE', 'AGRAVDOENC', 'AGRAVOUTRA', 'RIFAMPICIN',
   'ISONIAZIDA', 'ETAMBUTOL', 'ESTREPTOMI', 'PIRAZINAMI', 'ETIONAMIDA', 'OUTRAS',
   'TRAT_SUPER', 'AGRAVDROGA', 'AGRAVTABAC', 'DOENCA_TRA'): {
    1: 'Yes',
    2: 'No',
    3: 'Not performed',
    9: 'Ignored',
  },
  ('BACILOS_E2', 'BACILOSC_O', 'BACILOSC_1', 'BACILOSC_2', 'BACILOSC_3', 'BACILOSC_4', 'BACILOSC_5', 'BACILOSC_6'): {
    1: 'Positive',
    2: 'Negative',
    3: 'Not performed',
    4: 'Not applicable',
    9: 'Ignored',
  },
  ('BACILOSC_E', 'CULTURA_ES', 'HIV'): {
    1: 'Positive',
    2: 'Negative',
    3: 'In progress',
    4: 'Not performed',
    9: 'Ignored',
  },
}

In [6]:
for feature, correlated_values in translate_numbers.items():
  if isinstance(feature, tuple):
    for feature in feature:
      df[feature] = df[feature].replace(to_replace=correlated_values.keys(), value=correlated_values.values())
  else:
    df[feature] = df[feature].replace(to_replace=correlated_values.keys(), value=correlated_values.values())

In [7]:
df

,DT_NOTIFIC,CS_SEXO,CS_RACA,TRATAMENTO,RAIOX_TORA,TESTE_TUBE,FORMA,AGRAVAIDS,AGRAVALCOO,AGRAVDIABE,...,BACILOSC_3,BACILOSC_4,BACILOSC_5,BACILOSC_6,SITUA_ENCE,AGRAVDROGA,AGRAVTABAC,UF,DIAS_EM_TRATAMENTO,IDADE
0,06/01/2001,Male,Ignored,New case,Suspicious,Not performed,Pulmonary,Ignored,Ignored,Ignored,...,Ignored,Not performed,Ignored,Not performed,Cured,Ignored,Ignored,AC,195,66.0
1,16/01/2001,Female,Admixed,New case,Suspicious,Not performed,Pulmonary,Ignored,Ignored,Ignored,...,Ignored,Not performed,Ignored,Not performed,Cured,Ignored,Ignored,AC,181,35.0
2,16/01/2001,Male,Admixed,New case,Suspicious,Not performed,Pulmonary,Ignored,Ignored,Ignored,...,Ignored,Not performed,Ignored,Not performed,Cured,Ignored,Ignored,AC,181,54.0
3,22/01/2001,Male,Admixed,New case,Suspicious,Not performed,Pulmonary,Ignored,Ignored,Ignored,...,Ignored,Not performed,Ignored,Not performed,Cured,Ignored,Ignored,AC,181,36.0
4,03/01/2001,Female,Ignored,New case,No accomplished,Not performed,Pulmonary,Ignored,Ignored,Ignored,...,Ignored,Not performed,Ignored,Not performed,Cured,Ignored,Ignored,AC,183,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964094,31/07/2019,Female,Admixed,New case,Suspicious,Not performed,Pulmonary,No,No,No,...,Negative,Negative,Negative,Negative,Cured,No,No,TO,190,32.0
964095,17/08/2019,Female,Admixed,New case,Suspicious,Not performed,Pulmonary,Ignored,No,No,...,Negative,Not performed,Negative,Negative,Cured,No,No,TO,214,24.0
964096,04/09/2019,Male,Admixed,New case,Suspicious,Not performed,Pulmonary,No,No,No,...,Negative,Not performed,Not performed,Not performed,Cured,No,No,TO,196,22.0
964097,27/09/2019,Male,Admixed,New case,No accomplished,Not performed,Extrapulmonary,No,No,No,...,Not applicable,Not applicable,Not applicable,Not applicable,Cured,No,No,TO,178,15.0
964098,11/12/2019,Male,Admixed,New case,Suspicious,Not performed,Pulmonary,No,No,No,...,Ignored,Ignored,Ignored,Ignored,Died,No,No,TO,54,87.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964099 entries, 0 to 964098
Data columns (total 38 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   DT_NOTIFIC          964099 non-null  object
 1   CS_SEXO             964099 non-null  object
 2   CS_RACA             964099 non-null  object
 3   TRATAMENTO          964099 non-null  object
 4   RAIOX_TORA          964099 non-null  object
 5   TESTE_TUBE          964099 non-null  object
 6   FORMA               964099 non-null  object
 7   AGRAVAIDS           964099 non-null  object
 8   AGRAVALCOO          964099 non-null  object
 9   AGRAVDIABE          964099 non-null  object
 10  AGRAVDOENC          964099 non-null  object
 11  AGRAVOUTRA          964099 non-null  object
 12  BACILOSC_E          964099 non-null  object
 13  BACILOS_E2          964099 non-null  object
 14  BACILOSC_O          964099 non-null  object
 15  CULTURA_ES          964099 non-null  object
 16  HIV                 964099 non-null  object
 17  RIFAMPICIN          964099 non-null  object
 18  ISONIAZIDA          964099 non-null  object
 19  ETAMBUTOL           964099 non-null  object
 20  ESTREPTOMI          964099 non-null  object
 21  PIRAZINAMI          964099 non-null  object
 22  ETIONAMIDA          964099 non-null  object
 23  OUTRAS              964099 non-null  object
 24  TRAT_SUPER          964099 non-null  object
 25  DOENCA_TRA          964099 non-null  object
 26  BACILOSC_1          964099 non-null  object
 27  BACILOSC_2          964099 non-null  object
 28  BACILOSC_3          964099 non-null  object
 29  BACILOSC_4          964099 non-null  object
 30  BACILOSC_5          964099 non-null  object
 31  BACILOSC_6          964099 non-null  object
 32  SITUA_ENCE          964099 non-null  object
 33  AGRAVDROGA          964099 non-null  object
 34  AGRAVTABAC          964099 non-null  object
 35  UF                  964098 non-null  object
 36  DIAS_EM_TRATAMENTO  964099 non-null  int64
 37  IDADE               964073 non-null  float64
dtypes: float64(1), int64(1), object(36)
memory usage: 279.5+ MB

In [9]:
df.isnull().sum()

DT_NOTIFIC             0
CS_SEXO                0
CS_RACA                0
TRATAMENTO             0
RAIOX_TORA             0
TESTE_TUBE             0
FORMA                  0
AGRAVAIDS              0
AGRAVALCOO             0
AGRAVDIABE             0
AGRAVDOENC             0
AGRAVOUTRA             0
BACILOSC_E             0
BACILOS_E2             0
BACILOSC_O             0
CULTURA_ES             0
HIV                    0
RIFAMPICIN             0
ISONIAZIDA             0
ETAMBUTOL              0
ESTREPTOMI             0
PIRAZINAMI             0
ETIONAMIDA             0
OUTRAS                 0
TRAT_SUPER             0
DOENCA_TRA             0
BACILOSC_1             0
BACILOSC_2             0
BACILOSC_3             0
BACILOSC_4             0
BACILOSC_5             0
BACILOSC_6             0
SITUA_ENCE             0
AGRAVDROGA             0
AGRAVTABAC             0
UF                     1
DIAS_EM_TRATAMENTO     0
IDADE                 26
dtype: int64

In [10]:
df = df.dropna()

In [11]:
df.duplicated().sum()

111

In [12]:
df = df.drop_duplicates()

In [13]:
df = df.reset_index(drop=True)

In [ ]:
df.to_parquet('../assets/SINAN-TB_Brazil_cleaned.parquet', index=None)