# Data Cleaning & Preprocessing

In [3]:
import pandas as pd
import seaborn as sns
from ydata_profiling import ProfileReport

In [10]:
df = pd.read_parquet('../assets/SINAN-TB_Brazil.parquet')
df

,DT_NOTIFIC,CS_SEXO,CS_RACA,TRATAMENTO,RAIOX_TORA,TESTE_TUBE,FORMA,AGRAVAIDS,AGRAVALCOO,AGRAVDIABE,...,BACILOSC_3,BACILOSC_4,BACILOSC_5,BACILOSC_6,SITUA_ENCE,AGRAVDROGA,AGRAVTABAC,UF,DIAS_EM_TRATAMENTO,IDADE
0,06/01/2001,1,9.0,1.0,1.0,4.0,1.0,9.0,9.0,9.0,...,9.0,3.0,9.0,3.0,1.0,9.0,9.0,AC,195,66.0
1,16/01/2001,0,4.0,1.0,1.0,4.0,1.0,9.0,9.0,9.0,...,9.0,3.0,9.0,3.0,1.0,9.0,9.0,AC,181,35.0
2,16/01/2001,1,4.0,1.0,1.0,4.0,1.0,9.0,9.0,9.0,...,9.0,3.0,9.0,3.0,1.0,9.0,9.0,AC,181,54.0
3,22/01/2001,1,4.0,1.0,1.0,4.0,1.0,9.0,9.0,9.0,...,9.0,3.0,9.0,3.0,1.0,9.0,9.0,AC,181,36.0
4,03/01/2001,0,9.0,1.0,4.0,4.0,1.0,9.0,9.0,9.0,...,9.0,3.0,9.0,3.0,1.0,9.0,9.0,AC,183,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
964094,31/07/2019,0,4.0,1.0,1.0,4.0,1.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,1.0,2.0,2.0,TO,190,32.0
964095,17/08/2019,0,4.0,1.0,1.0,4.0,1.0,9.0,2.0,2.0,...,2.0,3.0,2.0,2.0,1.0,2.0,2.0,TO,214,24.0
964096,04/09/2019,1,4.0,1.0,1.0,4.0,1.0,2.0,2.0,2.0,...,2.0,3.0,3.0,3.0,1.0,2.0,2.0,TO,196,22.0
964097,27/09/2019,1,4.0,1.0,4.0,4.0,2.0,2.0,2.0,2.0,...,4.0,4.0,4.0,4.0,1.0,2.0,2.0,TO,178,15.0
964098,11/12/2019,1,4.0,1.0,1.0,4.0,1.0,2.0,2.0,2.0,...,9.0,9.0,9.0,9.0,3.0,2.0,2.0,TO,54,87.0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964099 entries, 0 to 964098
Data columns (total 38 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   DT_NOTIFIC          964099 non-null  object
 1   CS_SEXO             964099 non-null  int64
 2   CS_RACA             964099 non-null  float64
 3   TRATAMENTO          964099 non-null  float64
 4   RAIOX_TORA          964099 non-null  float64
 5   TESTE_TUBE          964099 non-null  float64
 6   FORMA               964099 non-null  float64
 7   AGRAVAIDS           964099 non-null  float64
 8   AGRAVALCOO          964099 non-null  float64
 9   AGRAVDIABE          964099 non-null  float64
 10  AGRAVDOENC          964099 non-null  float64
 11  AGRAVOUTRA          964099 non-null  float64
 12  BACILOSC_E          964099 non-null  float64
 13  BACILOS_E2          964099 non-null  float64
 14  BACILOSC_O          964099 non-null  float64
 15  CULTURA_ES          964099 non-null  float64
 16  HIV                 964099 non-null  float64
 17  RIFAMPICIN          964099 non-null  float64
 18  ISONIAZIDA          964099 non-null  float64
 19  ETAMBUTOL           964099 non-null  float64
 20  ESTREPTOMI          964099 non-null  float64
 21  PIRAZINAMI          964099 non-null  float64
 22  ETIONAMIDA          964099 non-null  float64
 23  OUTRAS              964099 non-null  float64
 24  TRAT_SUPER          964099 non-null  float64
 25  DOENCA_TRA          964099 non-null  float64
 26  BACILOSC_1          964099 non-null  float64
 27  BACILOSC_2          964099 non-null  float64
 28  BACILOSC_3          964099 non-null  float64
 29  BACILOSC_4          964099 non-null  float64
 30  BACILOSC_5          964099 non-null  float64
 31  BACILOSC_6          964099 non-null  float64
 32  SITUA_ENCE          964099 non-null  float64
 33  AGRAVDROGA          964099 non-null  float64
 34  AGRAVTABAC          964099 non-null  float64
 35  UF                  964098 non-null  object
 36  DIAS_EM_TRATAMENTO  964099 non-null  int64
 37  IDADE               964073 non-null  float64
dtypes: float64(34), int64(2), object(2)
memory usage: 279.5+ MB